[package]
name = "achernar"
version = "0.1.0"
authors = ["gpi <gpimpale29@gmail.com>"]
edition = "2021"

[dependencies]
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
num-bigint =  { version = "0.4.3", features = ["serde"] }
num-rational = { version = "0.4.0", features = ["serde"] }
num-traits = "0.2.15"
lsp-types = "0.93.0"
peekmore = "1.0.0"
strum = { version = "0.24.1", features = ["derive"] }
bumpalo = { version = "3.10.0", features = ["allocator_api"] }
hashbrown = { version = "0.12.1", features = ["nightly"] }
