[package]
name = "achernar"
version = "0.1.0"
authors = ["gpi <gpimpale29@gmail.com>"]
edition = "2021"

[dependencies]
serde_json = "1.0.80"
serde = { version = "1.0.136", features = ["derive"] }
num-bigint =  { version = "0.4.3", features = ["serde"] }
num-rational = { version = "0.4.0", features = ["serde"] }
num-traits = "0.2.14"
lsp-types = "0.93.0"
peekmore = "1.0.0"
strum = { version = "0.24.0", features = ["derive"] }
bumpalo = { version = "3.9.1", features = ["allocator_api"] }
hashbrown = { version = "0.12.0", features = ["nightly"] }
z3 = "0.11.2"
