[package]
name = "achernar"
version = "0.1.0"
authors = ["gpi <gpimpale29@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
num-bigint = "^0.4"
num-rational = "^0.4"
num-traits = "^0.2"
lsp-types = "^0.88"
peekmore = "^1.0.0"
