#include "token.h"
#include <stdlib.h>
#include <string.h>

com_str tk_strKind(tk_Kind val) {
  switch (val) {
  case tk_Eof:
    return com_str_lit_m("Eof");
  case tk_None:
    return com_str_lit_m("None");
  case tk_Identifier:
    return com_str_lit_m("Identifier");
  case tk_Never:
    return com_str_lit_m("Never");
  case tk_Loop:
    return com_str_lit_m("Loop");
  case tk_Match:
    return com_str_lit_m("Match");
  case tk_Val:
    return com_str_lit_m("Val");
  case tk_Return:
    return com_str_lit_m("Return");
  case tk_Defer:
    return com_str_lit_m("Defer");
  case tk_Fn:
    return com_str_lit_m("Fn");
  case tk_Pat:
    return com_str_lit_m("Pat");
  case tk_As:
    return com_str_lit_m("As");
  case tk_Struct:
    return com_str_lit_m("Struct");
  case tk_Enum:
    return com_str_lit_m("Enum");
  case tk_Type:
    return com_str_lit_m("Type");
  case tk_Namespace:
    return com_str_lit_m("Namespace");
  case tk_Use:
    return com_str_lit_m("Use");
  case tk_Nil:
    return com_str_lit_m("Nil");
  case tk_Bool:
    return com_str_lit_m("Bool");
  case tk_String:
    return com_str_lit_m("String");
  case tk_Char:
    return com_str_lit_m("Char");
  case tk_Float:
    return com_str_lit_m("Float");
  case tk_Int:
    return com_str_lit_m("Int");
  case tk_Negate:
    return com_str_lit_m("Negate");
  case tk_Posit:
    return com_str_lit_m("Posit");
  case tk_Add:
    return com_str_lit_m("Add");
  case tk_Sub:
    return com_str_lit_m("Sub");
  case tk_Mul:
    return com_str_lit_m("Mul");
  case tk_Div:
    return com_str_lit_m("Div");
  case tk_Mod:
    return com_str_lit_m("Mod");
  case tk_And:
    return com_str_lit_m("And");
  case tk_Or:
    return com_str_lit_m("Or");
  case tk_Not:
    return com_str_lit_m("Not");
  case tk_CompEqual:
    return com_str_lit_m("CompEqual");
  case tk_CompNotEqual:
    return com_str_lit_m("CompNotEqual");
  case tk_CompLess:
    return com_str_lit_m("CompLess");
  case tk_CompLessEqual:
    return com_str_lit_m("CompLessEqual");
  case tk_CompGreater:
    return com_str_lit_m("CompGreater");
  case tk_CompGreaterEqual:
    return com_str_lit_m("CompGreaterEqual");
  case tk_Ref:
    return com_str_lit_m("Ref");
  case tk_Deref:
    return com_str_lit_m("Deref");
  case tk_Define:
    return com_str_lit_m("Define");
  case tk_Assign:
    return com_str_lit_m("Assign");
  case tk_AssignAdd:
    return com_str_lit_m("AssignAdd");
  case tk_AssignSub:
    return com_str_lit_m("AssignSub");
  case tk_AssignMul:
    return com_str_lit_m("AssignMul");
  case tk_AssignDiv:
    return com_str_lit_m("AssignDiv");
  case tk_AssignMod:
    return com_str_lit_m("AssignMod");
  case tk_Pipe:
    return com_str_lit_m("Pipe");
  case tk_Arrow:
    return com_str_lit_m("Arrow");
  case tk_ScopeResolution:
    return com_str_lit_m("ScopeResolution");
  case tk_Tuple:
    return com_str_lit_m("Tuple");
  case tk_Union:
    return com_str_lit_m("Union");
  case tk_Underscore:
    return com_str_lit_m("Underscore");
  case tk_ParenLeft:
    return com_str_lit_m("ParenLeft");
  case tk_ParenRight:
    return com_str_lit_m("ParenRight");
  case tk_BracketLeft:
    return com_str_lit_m("BracketLeft");
  case tk_BracketRight:
    return com_str_lit_m("BracketRight");
  case tk_BraceLeft:
    return com_str_lit_m("BraceLeft");
  case tk_BraceRight:
    return com_str_lit_m("BraceRight");
  case tk_FieldAccess:
    return com_str_lit_m("FieldAccess");
  case tk_Colon:
    return com_str_lit_m("Colon");
  case tk_Semicolon:
    return com_str_lit_m("Semicolon");
  case tk_Backtick:
    return com_str_lit_m("Backtick");
  case tk_Rest:
    return com_str_lit_m("Rest");
  case tk_Dollar:
    return com_str_lit_m("Dollar");
  case tk_Label:
    return com_str_lit_m("Label");
  case tk_Macro:
    return com_str_lit_m("Macro");
  case tk_Comment:
    return com_str_lit_m("Comment");
  }
  abort();
}
